nodeLinker: node-modules

npmRegistries:
  //gitlab.com/api/v4/projects/45935297/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: glpat-yJS2wzy27zssquFGV5pe

npmScopes:
  tokene-q:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/45935297/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/projects/45935297/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
