nodeLinker: node-modules

npmRegistries:
  //gitlab.com/api/v4/projects/45935297/packages/npm/:
    npmAlwaysAuth: true
    #npmAuthToken: "${CI_JOB_TOKEN}"
    npmAuthToken: "glpat-3GsL3ayXZB-K5i_o6Umt"

npmScopes:
  tokene-q:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/45935297/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/projects/45935297/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
